package ru.trandefil.sc.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-12T19:03:24.718+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.sc.trandefil.ru/", name = "UserEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndPoint {

    @WebMethod
    @RequestWrapper(localName = "deleteUserByName", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.DeleteUserByName")
    @ResponseWrapper(localName = "deleteUserByNameResponse", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.DeleteUserByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteUserByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.UpdateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.sc.endpoint.User updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.trandefil.sc.endpoint.User arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.GetUserByName")
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.GetUserByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.sc.endpoint.User getUserByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "saveUser", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.SaveUser")
    @ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.SaveUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.sc.endpoint.User saveUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.GetAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.trandefil.sc.endpoint.User> getAllUsers();

    @WebMethod
    @RequestWrapper(localName = "getLoggedUser", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.GetLoggedUser")
    @ResponseWrapper(localName = "getLoggedUserResponse", targetNamespace = "http://endpoint.sc.trandefil.ru/", className = "ru.trandefil.sc.endpoint.GetLoggedUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.sc.endpoint.User getLoggedUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
